### PR TITLE
Update client methods

### PR DESCRIPTION
**Pull request by saifabid**
Will squash and merge with detailed commit message once we review this.

Pretty much the summary of the changes:
- Each struct's properties should be defined in their respective files (response, entity, intent) so those got separated into their own files 
- Refactored TextRequest and FileRequest to be A) consistent with one another in terms of code style B) json response handling is also much better now 
- Generally updated how responses are unmarshalled. This _**way**_ faster than the old way
- Added just about 100% test coverage for TextRequest.

@ftriquet review ?

### CODE REVIEW

**Comment by saifabid** [comment]
@ftriquet update the spelling mistake in the commit for the last commit, then I'd probably merge this in and start a new branch for further changes. The changes in this one are getting a bit long ?

**Comment by ftriquet** [comment]
@saifabid I think we are almost done. I had to change the parsing of the JSON for entities because the structures doesn't match the JSON, maybe there is a more effective way to do it? If it's ok for you I'll merge into develop and we can continue from there.

**Comment by saifabid** [comment]
@ftriquet yeah sounds good. Go ahead and merge. Which commit are you referring to with this ? `"I had to change the parsing of the JSON for entities because the structures doesn't match the JSON, maybe there is a more effective way to do it?" `

**Comment by saifabid** [comment]
:shipit: im good with you merging

**Comment by ftriquet** [comment]
@saifabid I'm refering to [this commit](https://github.com/RecastAI/SDK-Golang/commit/5d2640b2690d4f2b307f2d19647314f4d49dce4c).

**Pull request merged**
